logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/firstspring?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    password-encoder: bcrypt
